  metadata-db:

  airflow-web:
    volumes:
      - ${AIRFLOW_DAG_FOLDER:-{airflow_dags_location}/{airflow_dags_env}}:/airflow/dags
      - {airflow_config_location}:/airflow/airflow.cfg
    {airflow_environment}

  airflow-scheduler:
    volumes:
      - ${AIRFLOW_DAG_FOLDER:-{airflow_dags_location}/{airflow_dags_env}}:/airflow/dags
      - {airflow_config_location}:/airflow/airflow.cfg
    {airflow_environment}

  airflow-worker:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${AIRFLOW_DAG_FOLDER:-{airflow_dags_location}/{airflow_dags_env}}:/airflow/dags
      - ${HOST_TEMPORARY_DIRECTORY:-/tmp/airflow}:/tmp/airflow
      - {airflow_config_location}:/airflow/airflow.cfg
    user: root
    environment:
      - AIRFLOW__WORKER__HOST_TEMPORARY_DIRECTORY=${HOST_TEMPORARY_DIRECTORY:-/tmp/airflow}
      {airflow_environment_inline}

  flower:
    volumes:
      - {airflow_config_location}:/airflow/airflow.cfg

  redis:
